checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - tests/*

build:
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run