language: python
cache: pip
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"
  - "nightly"
install: "pip install discord.py pluginbase psutil pyparsing pyspeedtest tqdm sphinx sphinx_rtd_theme mypy pylint"
script:
  - mypy main.py api/*.py libs/*.py plugins/*.py --ignore-missing-imports
  - cd docs && make html